src/main/java/nl/sogeti/demo/model/Product.java
package nl.sogeti.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

/**
 * The JPA entity class that models the domain object Person. The primary key
 * (id) is generated.
 * 
 * @author Erwin
 * 
 */
@Entity
public class Product implements Serializable {

    private static final long serialVersionUID = 982374691237864L;

    @Id
    @GeneratedValue
    private Long id;
    
    
    @Column(scale = 2, precision = 3)
    private BigDecimal price;
    
    @NotNull
    @Column(updatable=false,unique=true)
    private String productId;
    
    private String name;

    public Product(){
	this.productId=UUID.randomUUID().toString();
    }
    
    public Long getId() {
	return id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    public String getName() {
	return name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public BigDecimal getPrice() {
	return price;
    }
    
    public BigDecimal getTotalPrice(int quantity) {
	if(this.getPrice()==null) return BigDecimal.ZERO; 
	return BigDecimal.valueOf(quantity).multiply((this.getPrice()));
    }

    public void setPrice(BigDecimal price) {
	this.price = price;
    }

    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((productId == null) ? 0 : productId.hashCode());
	return result;
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj) return true;
	if (obj == null) return false;
	if (getClass() != obj.getClass()) return false;
	Product other = (Product) obj;
	if (productId == null) {
	    if (other.productId != null) return false;
	} else if (!productId.equals(other.productId)) return false;
	return true;
    }


    
    

}

src/main/java/nl/sogeti/demo/model/ShoppingBasket.java
package nl.sogeti.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;


public class ShoppingBasket {

    private Map<Product,Integer> products = new HashMap<>();
    
    public void addProduct(Product product){
	Integer quantity = products.get(product);
	if(quantity == null){
	    quantity =0;
	}
	products.put(product, ++quantity);
    }
    
    public List<Entry<Product,Integer>> getProducts(){
	return new ArrayList<Entry<Product, Integer>>(this.products.entrySet());
    }
    
    public void removeProduct(Product product){
	if(products.containsKey(product)){
	    int quantity = products.get(product);
	    if(quantity == 1){
		products.remove(product);
	    } else {
		products.put(product, --quantity);
	    }
	}
    }
    
    public int getSize(){
	int size = 0;
	for(Entry<Product, Integer> entry : products.entrySet()){
	    size +=entry.getValue();
	}
	return size;
    }
    
    public BigDecimal getOrderTotal(){
	BigDecimal total = BigDecimal.valueOf(0, 2);
	for(Entry<Product, Integer> entry : products.entrySet()){
	    total=total.add(entry.getKey().getTotalPrice(entry.getValue()));
	}
	return total;
    }
}

src/main/java/nl/sogeti/demo/controller/ShopBean.java
package nl.sogeti.demo.controller;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import nl.sogeti.demo.model.Product;
import nl.sogeti.demo.model.ShoppingBasket;
import nl.sogeti.demo.service.CrudService;

/**
 * This is the JSF managed bean that handles calls from the home.xhtml This
 * class uses the PersonService EJB, injected by the container by use of the @Inject
 * annotation.
 * 
 * @author Erwin
 * 
 */
@ManagedBean
@SessionScoped
public class ShopBean implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    Logger logger;

    @Inject
    CrudService crudService;
    
    private ShoppingBasket shoppingBasket;
    
    public ShopBean(){
	this.shoppingBasket = new ShoppingBasket();
    }
    
    public ShoppingBasket getShoppingBasket(){
	return this.shoppingBasket;
    }
    

    public List<Product> list() {
	return crudService.findAll(Product.class);
    }

}

src/main/webapp/basket.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Shopping basket</title>
</h:head>
<h:body>
	<h:form>
		<h:outputText value="Shoppingbasket(#{shopBean.shoppingBasket.size})" />
		<h:dataTable id="productTable" var="entry"
			value="#{shopBean.shoppingBasket.products}">
			<h:column>
				<h:panelGrid>
					<h:outputText value="#{entry.key.name}" />
						<h:outputText value="#{entry.value} x #{entry.key.price} = #{entry.key.getTotalPrice(entry.value)}"/>
					<h:commandLink value="Remove"
						action="#{shopBean.shoppingBasket.removeProduct(entry.key)}" />
				</h:panelGrid>
			</h:column>
		</h:dataTable>
		<h:outputLink value="shop.xhtml">
			<h:outputText value="continue shopping" />
		</h:outputLink>
		<br></br>
		<h:outputLink value="checkout.xhtml">
			<h:outputText value="checkout $ #{shopBean.shoppingBasket.orderTotal}" />
		</h:outputLink>
	</h:form>
</h:body>
</html>

src/main/webapp/shop.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Webshop</title>
</h:head>
<h:body>
	<h:form>
		<h:outputLink value="basket.xhtml">
			<h:outputText value="Shoppingbasket(#{shopBean.shoppingBasket.size} | $ #{shopBean.shoppingBasket.orderTotal})" />
		</h:outputLink>
		<h:dataTable id="productTable" var="product"
			value="#{shopBean.list()}">
			<h:column>
				<h:panelGrid rendered="#{not empty product.name}">
					<h:outputText value="#{product.name}" />
					<h:outputText value="#{product.price}" />
					<h:commandLink value="Add to shopping basket"
						action="#{shopBean.shoppingBasket.addProduct(product)}" />
				</h:panelGrid>
			</h:column>
		</h:dataTable>
	</h:form>
</h:body>
</html>